# Generated by Django 4.2.7 on 2024-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
