# Generated by Django 4.2.7 on 2024-01-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
