# Generated by Django 4.2.7 on 2024-01-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_alter_customers_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
    ]
